routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
});

Route::middleware(['auth','role:Admin|Teacher|Student|Committee'])->group(function () {

    // For Notes
    Route::resource('/note', 'admin\NoteController')->middleware('role:Admin');

    // For Change Password
    Route::get('/change_password', 'admin\DashboradController@changepassword')->name('change.password');
    Route::post('/updatepassword', 'admin\DashboradController@updatepassword')->name('update.password');

    // For Group scheduler
    Route::get('/scheduler', 'admin\GroupSchedulerController@index')->name('index.scheduler');
    Route::post('/scheduler', 'admin\GroupSchedulerController@generate')->name('store.scheduler')->middleware('role:Admin');

    //For Date of submission
    Route::get('/setdates', 'admin\DateofSubmissionController@index')->name('index.date')->middleware('role:Admin');
    Route::post('/storedate', 'admin\DateofSubmissionController@store')->name('store.date')->middleware('role:Admin');
    Route::get('/editdate/{id}', 'admin\DateofSubmissionController@edit')->name('edit.date')->middleware('role:Admin');
    Route::post('/updatedate', 'admin\DateofSubmissionController@update')->name('update.date')->middleware('role:Admin');

    //For Marks
    Route::get('/adminviewmarks', 'Student\ViewMarksController@adminviewmarks')->name('admin.showmarks')->middleware('role:Admin');

    //For All Activites Show
    Route::get('/adminactivity', 'Teacher\ActivityController@adminindex')->name('all.adminactivity')->middleware('role:Admin');
    Route::get('/detialsactivity/{id}', 'Teacher\ActivityController@adminviewactivity')->name('details.activity')->middleware('role:Admin');

    // For View of Pervious FYP Data
    Route::get('/perviousfyp', 'admin\LastFypDataController@index')->name('all.lastfyp');
    Route::get('/newperviousfyp', 'admin\LastFypDataController@edit_data')->name('new.lastfyp')->middleware('role:Admin');
    Route::post('/storeperviousfyp', 'admin\LastFypDataController@store_data')->name('store.lastfyp')->middleware('role:Admin');
    Route::get('/deleteperviousfyp/{id}', 'admin\LastFypDataController@deleteperviousfyp')->name('delete.lastfyp')->middleware('role:Admin');
    Route::get('keywordserach', 'admin\LastFypDataController@keywordserach' )->name('keyword.search');

    // Admin Side
    Route::get('/dashboard', 'admin\DashboradController@index')->name('dashboard');
    Route::resource('/teacher', 'admin\TeacherController')->middleware('role:Admin');
    Route::resource('/student', 'admin\StudentController')->middleware('role:Admin');
    Route::post('/import', 'admin\ImportController@stdImport')->name('import.student')->middleware('role:Admin');
    Route::post('/thimport', 'admin\ImportController@TeacherImport')->name('import.teacher')->middleware('role:Admin');

    //Slots of All Teacher
    Route::get('/allslots', 'admin\AllSlotsController@index')->name('slots');

    //All Groups
    Route::get('/allgroups', 'admin\GroupsController@index')->name('admin.groups');
    Route::get('/groupdetials/{id}', 'admin\GroupsController@groupdetials')->name('detials.groups');
    Route::post('/assigngroup', 'admin\GroupsController@assigngroup')->name('assign.groups');

    // For Committee Members
    Route::get('/committee', 'admin\CommitteController@index')->name('all.committee')->middleware('role:Admin');
    Route::post('/committee', 'admin\CommitteController@store')->name('store.committee')->middleware('role:Admin');

    // Student Side
    Route::group(['middlerware' => 'role:Student'], function() {

        // For Scheduler
        Route::get('/stdschedule', 'Student\SchedulerController@index')->name('std.scheduler')->middleware('role:Student');


        // For add group student
        Route::get('/group', 'Student\StudentGroupController@viewgroup')->name('view.group')->middleware('role:Student');
        Route::post('/group', 'Student\StudentGroupController@addgroup')->name('add.group')->middleware('role:Student');

        // For Proposal Update
        Route::post('/upproposal', 'Student\StudentGroupController@updateProposal')->name('up.proposal')->middleware('role:Student');

        // For Marks
        Route::get('/viewmarks', 'Student\ViewMarksController@viewmarks')->name('show.marks')->middleware('role:Student');

        // For Activity Store
        Route::get('/stdactivity', 'Teacher\ActivityController@stdindex')->name('std.activity')->middleware('role:Student');
        Route::get('/viewstdactivity/{id}', 'Teacher\ActivityController@stdactivityview')->name('view.activity')->middleware('role:Student');
        Route::post('/storestdactivity', 'Teacher\ActivityController@stdstore')->name('store.stdactivity')->middleware('role:Student');


    });

    // Teacher Side
    Route::group(['middlerware' => 'role:Teacher'], function() {

        // For Panel Meeting
        Route::get('/panelmeeting', 'admin\GroupSchedulerController@panelindex')->name('panel.meeting')->middleware('role:Teacher');
        Route::post('/panelmeeting', 'committe\SchedulerController@panelmeetingstatus')->name('panelmeeting.store');
        Route::get('/groupfeedback/{id}', 'Teacher\MarksController@groupfeedback')->name('group.feeback');


        // For Group
        Route::get('/request/{id}', 'Teacher\TeacherGroupController@viewgrouprequest')->name('view.grouprequest')->middleware('role:Teacher');
        Route::get('/download/{id}', 'Teacher\TeacherGroupController@downloadproposal')->name('download.proposal')->middleware('role:Teacher');
        Route::post('/approved-group/{id}', 'Teacher\TeacherGroupController@groupapproved')->name('group.approved')->middleware('role:Teacher');
        Route::post('/rejected-group/{id}', 'Teacher\TeacherGroupController@groupRejected')->name('group.rejected')->middleware('role:Teacher');
        Route::get('/groups', 'Teacher\TeacherGroupController@groups')->name('all.groups')->middleware('role:Teacher');

        // For Marks
        Route::get('/marks', 'Teacher\MarksController@index')->name('group.marks')->middleware('role:Teacher');
        Route::get('/groupmarks/{id}', 'Teacher\MarksController@groupmarks')->name('add.marks')->middleware('role:Teacher');
        Route::get('/add-marks/{groupid}/{studentid}','Teacher\MarksController@edit')->name('marks.edit')->middleware('role:Teacher');
        Route::post('/add-marks/{groupid}/{studentid}','Teacher\MarksController@edit')->name('marks.edit')->middleware('role:Teacher');

        // For Slots
        Route::get('/slots', 'Teacher\SlotController@index')->name('all.slots')->middleware('role:Teacher|Student');
        Route::post('/addslots', 'Teacher\SlotController@store')->name('store.slots')->middleware('role:Teacher');
        Route::get('/editslots/{id}', 'Teacher\SlotController@edit')->name('edit.slots')->middleware('role:Teacher');
        Route::post('/updateslots/{id}', 'Teacher\SlotController@update')->name('update.slots')->middleware('role:Teacher');
        Route::get('/deleteslots/{id}', 'Teacher\SlotController@delete')->name('delete.slots')->middleware('role:Teacher');


        // For Activities
        Route::get('/activity', 'Teacher\ActivityController@index')->name('all.activity')->middleware('role:Teacher');
        Route::get('/newactivity', 'Teacher\ActivityController@create')->name('new.activity')->middleware('role:Teacher');
        Route::post('/storeactivity', 'Teacher\ActivityController@store')->name('store.activity')->middleware('role:Teacher');
        Route::get('/editactivity/{id}', 'Teacher\ActivityController@editactivity')->name('edit.activity')->middleware('role:Teacher');
        Route::post('/updateactivity', 'Teacher\ActivityController@updateactivity')->name('update.activity')->middleware('role:Teacher');
        Route::get('/viewactivity/{id}', 'Teacher\ActivityController@viewactivity')->name('view.thactivity')->middleware('role:Teacher');

        // For My Porposal
        Route::get('/proposal', 'Teacher\MyPorposalController@index')->name('all.proposal')->middleware('role:Teacher');
        Route::post('/storeproposal', 'Teacher\MyPorposalController@store')->name('store.proposal')->middleware('role:Teacher');
        Route::get('/editproposal/{id}', 'Teacher\MyPorposalController@edit')->name('edit.proposal')->middleware('role:Teacher');
        Route::post('/updateproposal/{id}', 'Teacher\MyPorposalController@update')->name('update.proposal')->middleware('role:Teacher');
        Route::get('/deleteproposal/{id}', 'Teacher\MyPorposalController@delete')->name('delete.proposal')->middleware('role:Teacher');

    });

    Route::group(['middlerware' => 'role:Committee'], function() {
        Route::post('/meetingresponse', 'committe\SchedulerController@meetingstatus')->name('store.response')->middleware('role:Committee');
        Route::get('/schedule', 'committe\SchedulerController@index')->name('show.scheduler');

    });
});
require __DIR__.'/auth.php';

app/Models/Group.php
<?php

namespace App\Models;

use App\Models\Teacher;
use App\Models\PivotGroup;
use App\Models\GroupComment;
use Facade\FlareClient\View;
use App\Models\PanelFeedback;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Group extends Model
{
    use HasFactory, Notifiable;

    protected $guarded = [];

    public function group() {
        return $this->belongsTo(PivotGroup::class,'id', 'group_id');
    }

    public function feedback() {
        return $this->belongsTo(PanelFeedback::class,'id', 'group_id');
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function getPathAttribute($value) {
        return asset('storage/'.$value);
    }

    public function comments(){
        return $this->belongsTo(GroupComment::class,'id', 'group_id');
    }
}

app/Models/Marks.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Marks extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function groups(){
        return $this->belongsTo(Group::class,'group_id', 'id');
    }

    public function student(){
        return $this->belongsTo(User::class,'student_id', 'id');
    }

    public function teacher(){
        return $this->belongsTo(User::class,'teacher_id', 'id');
    }
}

app/Http/Controllers/Teacher/MarksController.php
<?php

namespace App\Http\Controllers\Teacher;

use App\Models\User;
use App\Models\Group;
use App\Models\PivotGroup;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Models\Marks;
use App\Http\Common\Helper;
use App\Models\GroupScheduler;
use App\Models\PanelFeedback;
use App\Models\SchudelPanel;

class MarksController extends Controller
{
    public function index(){

        $data['page_slug'] = request()->route()->uri();

        $data['groups'] = Group::with('feedback')->whereHas('group', function ($query) {
            return $query->where(['teacher_id' => Auth::id(), 'is_approved' => 1]);
        })->get();
        // $checkteacher = SchudelPanel::where('teacher_id', Auth::id())->get();
        // dd($checkteacher);
        return view('fyp.TeacherSide.Marks.groupmarks' , $data);

    }

    public function groupmarks(Request $request, $id){

        $data['page_slug'] = request()->route()->uri();
        $group_id = $id;
        $tt_id = Auth::id();
        $data['students'] = User::whereHas('stdgroup', function ($query) use($group_id) {
            return $query->where('group_id', '=', $group_id);
        })->get();
        $data['groupdata'] = Group::find($id);
        // dd($data['students']);
        return view('fyp.TeacherSide.Marks.edit-groupmarks' , $data);

    }

    public function edit(Request $request, $groupid,$studentid){

        if($request->isMethod('post')){

        $group_id = $groupid;
        $student_id = $studentid;
        $teacher_id = Auth::id();
        $request->validate([
            'midevolution'=>'required|numeric|min:0|max:40',
            'midyearevolution'=>'required|numeric|min:0|max:60',
            'finalyearevolution'=>'required|numeric|min:0|max:100',
            ]);

            $data =[
                'group_id'=> $group_id,
                'student_id'=> $student_id,
                'teacher_id'=> $teacher_id,
                'mid_semester_evaluation'=>$request->midevolution,
                'mid_year_evaluation'=>$request->midyearevolution,
                'final_year_evaluation'=>$request->finalyearevolution,
            ];

            if($request->islocked_mid_marks){
                $data['islocked_mid_marks'] = 1;

            }

            if($request->islocked_midyear_marks){
                $data['islocked_midyear_marks'] = 1;

            }

            if($request->islocked_finalyear_marks){
                $data['islocked_finalyear_marks'] = 1;

            }


            $occur = marks::where('student_id',$student_id)->first();

            if($occur != null){

                marks::where('student_id',$student_id)->update($data);
                Helper::toast('success','Successfully Updated');

            }else {

            marks::create($data);
            Helper::toast('success','Successfully Added');

            }
            // return $data;
            return redirect(route('group.marks'));

        }
        else {

            $data['page_slug'] = request()->route()->uri();
            $group_id = $groupid;
            $student_id = $studentid;
            $tt_id = Auth::id();
            $data['students'] = User::whereHas('stdgroup', function ($query) use($group_id,$student_id) {
                return $query->where(['group_id'=> $group_id,'student_id'=> $student_id]);
            })->get();
            $data['groupdata'] = Group::find($group_id);
            $data['stdmarks'] = marks::where('student_id',$student_id)->first();

            // dd($data['stdmarks']);
            return view('fyp.TeacherSide.Marks.add_marks' , $data);

        }

    }

    public function groupfeedback($id){

        $feedback = PanelFeedback::with('teacher')->where('group_id',$id)->get();
        return response()->json($feedback);
    }
}

resources/views/fyp/TeacherSide/Marks/edit-groupmarks.blade.php
@extends('fyp.layouts.app')
@section('content')
<div class="d-flex flex-column" id="kt_wrapper">

    @extends('fyp.layouts.head')

    <!--begin::Content-->
    <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
        <!--begin::Entry-->
        <div class="d-flex flex-column-fluid">
            <!--begin::Container-->
            <div class="container">
                <!--begin::Dashboard-->
                <div class="row">
                    <div class="col-xl-12">
                        <!--begin::List Widget 2-->
                        <div class="card card-custom bg-light-success card-stretch gutter-b">
                            <!--begin::Header-->
                            <div class="card-header border-0 pt-6 mb-2">
                                <h3 class="card-title align-items-start flex-column">
                                    <span class="card-label font-weight-bold font-size-h4 text-dark-75 mb-3">{{ $groupdata->title}}</span>
                                    <span class="text-muted font-weight-bold font-size-sm">{{ $groupdata->description}}</span>
                                </h3>
                                {{-- <div class="card-toolbar">
                                    <button class="btn btn-light-primary btn-sm btn-shadow font-weight-bolder font-size-sm" data-toggle="modal" data-target="#projectporposal">
                                        Project Proposal &nbsp;<i class="fas fa-eye"></i>
                                    </button>
                                    &nbsp;
                                    &nbsp;
                                    <a href="{{ route('download.proposal', $groupdata->id) }}" class="btn btn-light-warning btn-sm btn-shadow font-weight-bolder font-size-sm">
                                        Project Proposal &nbsp;<i class="fas fa-file-download"></i>
                                    </a>
                                </div> --}}
                            </div>
                            <!--end::Header-->
                            <!--begin::Body-->
                            <div class="card-body pt-2">
                                @foreach ($students as $student)

                                <div class="card-toolbar">
                                    <a href="{{route('marks.edit',['groupid' =>$groupdata->id,'studentid'=>$student->id])}}" class="btn btn-success btn-sm btn-shadow font-weight-bolder font-size-sm float-right active">
                                        Add Marks &nbsp;<i class="fas fa-check-circle"></i></a>
                                    </div>

                                <!--begin::Item-->
                                <div class="d-flex align-items-center mb-10">
                                    <!--begin::Symbol-->
                                    <div class="symbol symbol-40 symbol-light-white mr-5">
                                        <div class="symbol-label">
                                            <img src="{{ URL:: asset('fyp/assets/media/svg/avatars/004-boy-1.svg')}}" class="h-75 align-self-end" alt="" />
                                        </div>
                                    </div>
                                    <!--end::Symbol-->
                                    <!--begin::Text-->
                                    <div class="d-flex flex-column font-weight-bold">
                                        <span class="text-dark text-hover-primary mb-2 font-size-lg">{{ $student->name}}
                                        </span>
                                        <span class="text-muted">{{$student->roll_no}}</span>
                                    </div>
                                    <!--end::Text-->
                                </div>
                                <!--end::Item-->
                                @endforeach
                            </div>
                            <!--end::Body-->
                        </div>
                        <!--end::List Widget 2-->
                    </div>
                </div>
                <!--end::Dashboard-->
            </div>
            <!--end::Container-->
        </div>
        <!--end::Entry-->
    </div>
    <!--end::Content-->
</div>

{{-- PDF Modal --}}
<!-- Modal-->
<div class="modal fade" id="projectporposal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdrop" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Project Propsal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            <div class="modal-body">
                <iframe src ="{{ asset($groupdata->path)}}" width="100%" height="500px"></iframe>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light-primary font-weight-bold" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/fyp/TeacherSide/Marks/groupmarks.blade.php
@extends('fyp.layouts.app')
@section('content')
<div class="row">
    @foreach ($groups as $index=> $data)
    <div class="col-xl-6">
        <!--begin::Stats Widget 1-->
        <div class="card card-custom bgi-no-repeat card-stretch gutter-b"
            style="background-position: right top; background-size: 30% auto; background-image: url(fyp/assets/media/svg/shapes/abstract-{{++$index}}.svg)">
            <!--begin::Body-->
            <div class="card-body">
                <a href="{{ route('add.marks', ['id' => $data->id])}}" class="card-title font-weight-bold text-muted text-hover-primary font-size-h5">{{$data->title}}</a>
                <div class="font-weight-bold text-success mt-9 mb-5">
                    @if ($data->feedback)
                        <a href="javascript:void(0)" onclick="groupdetials({{$data->id}})" class="btn btn-light-primary">Panel Feedback</a>
                    @else
                        <span class="p-4 badge badge-primary" style="font-size: 13px;">No Feeback Yet</span>
                    @endif
                </div>
                <p class="text-dark-75 font-weight-bolder font-size-h5 m-0">{{$data->description}}</p>
            </div>
            <!--end::Body-->
        </div>
        <!--end::Stats Widget 1-->
    </div>
    @endforeach
</div>
<!-- Modal-->
<div class="modal fade" id="groupdetials" data-backdrop="static" tabindex="-1" role="dialog"
    aria-labelledby="staticBackdrop" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Group Details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xl-12">
                        <!--begin::List Widget 2-->
                        <div class="card card-custom bg-light-success">
                            <!--begin::Body-->
                            <div class="card-body pt-10">
                                <!--begin::Item-->
                                <div class="" id="student">

                                </div>
                                <!--end::Item-->
                            </div>
                            <!--end::Body-->
                        </div>
                        <!--end::List Widget 2-->
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light-primary font-weight-bold" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
@endsection
@section('footer.scripts')
<script>

    function groupdetials(id) {
        $.get('groupfeedback/'+id, function (data) {
            var feedback = data;
            console.log(data);
            $("#student").empty();

            var my_orders = $("#student");


            $.each(feedback, function(i,comments){

                my_orders.append('<div class="d-flex align-items-center mb-10"><div class="d-flex flex-column font-weight-bold"><span class="text-dark text-hover-primary mb-1 font-size-lg">'+comments.teacher.name+'</span><span class="text-muted">'+comments.feedback+'</span></div></div>');

            });
            $("#groupdetials").modal('toggle');

        });
    }

</script>
@endsection