routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
});

Route::middleware(['auth','role:Admin|Teacher|Student|Committee'])->group(function () {

    // For Notes
    Route::resource('/note', 'admin\NoteController')->middleware('role:Admin');

    // For Change Password
    Route::get('/change_password', 'admin\DashboradController@changepassword')->name('change.password');
    Route::post('/updatepassword', 'admin\DashboradController@updatepassword')->name('update.password');

    // For Group scheduler
    Route::get('/scheduler', 'admin\GroupSchedulerController@index')->name('index.scheduler');
    Route::post('/scheduler', 'admin\GroupSchedulerController@generate')->name('store.scheduler')->middleware('role:Admin');

    //For Date of submission
    Route::get('/setdates', 'admin\DateofSubmissionController@index')->name('index.date')->middleware('role:Admin');
    Route::post('/storedate', 'admin\DateofSubmissionController@store')->name('store.date')->middleware('role:Admin');
    Route::get('/editdate/{id}', 'admin\DateofSubmissionController@edit')->name('edit.date')->middleware('role:Admin');
    Route::post('/updatedate', 'admin\DateofSubmissionController@update')->name('update.date')->middleware('role:Admin');

    //For Marks
    Route::get('/adminviewmarks', 'Student\ViewMarksController@adminviewmarks')->name('admin.showmarks')->middleware('role:Admin');

    //For All Activites Show
    Route::get('/adminactivity', 'Teacher\ActivityController@adminindex')->name('all.adminactivity')->middleware('role:Admin');
    Route::get('/detialsactivity/{id}', 'Teacher\ActivityController@adminviewactivity')->name('details.activity')->middleware('role:Admin');

    // For View of Pervious FYP Data
    Route::get('/perviousfyp', 'admin\LastFypDataController@index')->name('all.lastfyp');
    Route::get('/newperviousfyp', 'admin\LastFypDataController@edit_data')->name('new.lastfyp')->middleware('role:Admin');
    Route::post('/storeperviousfyp', 'admin\LastFypDataController@store_data')->name('store.lastfyp')->middleware('role:Admin');
    Route::get('/deleteperviousfyp/{id}', 'admin\LastFypDataController@deleteperviousfyp')->name('delete.lastfyp')->middleware('role:Admin');
    Route::get('keywordserach', 'admin\LastFypDataController@keywordserach' )->name('keyword.search');

    // Admin Side
    Route::get('/dashboard', 'admin\DashboradController@index')->name('dashboard');
    Route::resource('/teacher', 'admin\TeacherController')->middleware('role:Admin');
    Route::resource('/student', 'admin\StudentController')->middleware('role:Admin');
    Route::post('/import', 'admin\ImportController@stdImport')->name('import.student')->middleware('role:Admin');
    Route::post('/thimport', 'admin\ImportController@TeacherImport')->name('import.teacher')->middleware('role:Admin');

    //Slots of All Teacher
    Route::get('/allslots', 'admin\AllSlotsController@index')->name('slots');

    //All Groups
    Route::get('/allgroups', 'admin\GroupsController@index')->name('admin.groups');
    Route::get('/groupdetials/{id}', 'admin\GroupsController@groupdetials')->name('detials.groups');
    Route::post('/assigngroup', 'admin\GroupsController@assigngroup')->name('assign.groups');

    // For Committee Members
    Route::get('/committee', 'admin\CommitteController@index')->name('all.committee')->middleware('role:Admin');
    Route::post('/committee', 'admin\CommitteController@store')->name('store.committee')->middleware('role:Admin');

    // Student Side
    Route::group(['middlerware' => 'role:Student'], function() {

        // For Scheduler
        Route::get('/stdschedule', 'Student\SchedulerController@index')->name('std.scheduler')->middleware('role:Student');


        // For add group student
        Route::get('/group', 'Student\StudentGroupController@viewgroup')->name('view.group')->middleware('role:Student');
        Route::post('/group', 'Student\StudentGroupController@addgroup')->name('add.group')->middleware('role:Student');

        // For Proposal Update
        Route::post('/upproposal', 'Student\StudentGroupController@updateProposal')->name('up.proposal')->middleware('role:Student');

        // For Marks
        Route::get('/viewmarks', 'Student\ViewMarksController@viewmarks')->name('show.marks')->middleware('role:Student');

        // For Activity Store
        Route::get('/stdactivity', 'Teacher\ActivityController@stdindex')->name('std.activity')->middleware('role:Student');
        Route::get('/viewstdactivity/{id}', 'Teacher\ActivityController@stdactivityview')->name('view.activity')->middleware('role:Student');
        Route::post('/storestdactivity', 'Teacher\ActivityController@stdstore')->name('store.stdactivity')->middleware('role:Student');


    });

    // Teacher Side
    Route::group(['middlerware' => 'role:Teacher'], function() {

        // For Panel Meeting
        Route::get('/panelmeeting', 'admin\GroupSchedulerController@panelindex')->name('panel.meeting')->middleware('role:Teacher');
        Route::post('/panelmeeting', 'committe\SchedulerController@panelmeetingstatus')->name('panelmeeting.store');
        Route::get('/groupfeedback/{id}', 'Teacher\MarksController@groupfeedback')->name('group.feeback');


        // For Group
        Route::get('/request/{id}', 'Teacher\TeacherGroupController@viewgrouprequest')->name('view.grouprequest')->middleware('role:Teacher');
        Route::get('/download/{id}', 'Teacher\TeacherGroupController@downloadproposal')->name('download.proposal')->middleware('role:Teacher');
        Route::post('/approved-group/{id}', 'Teacher\TeacherGroupController@groupapproved')->name('group.approved')->middleware('role:Teacher');
        Route::post('/rejected-group/{id}', 'Teacher\TeacherGroupController@groupRejected')->name('group.rejected')->middleware('role:Teacher');
        Route::get('/groups', 'Teacher\TeacherGroupController@groups')->name('all.groups')->middleware('role:Teacher');

        // For Marks
        Route::get('/marks', 'Teacher\MarksController@index')->name('group.marks')->middleware('role:Teacher');
        Route::get('/groupmarks/{id}', 'Teacher\MarksController@groupmarks')->name('add.marks')->middleware('role:Teacher');
        Route::get('/add-marks/{groupid}/{studentid}','Teacher\MarksController@edit')->name('marks.edit')->middleware('role:Teacher');
        Route::post('/add-marks/{groupid}/{studentid}','Teacher\MarksController@edit')->name('marks.edit')->middleware('role:Teacher');

        // For Slots
        Route::get('/slots', 'Teacher\SlotController@index')->name('all.slots')->middleware('role:Teacher|Student');
        Route::post('/addslots', 'Teacher\SlotController@store')->name('store.slots')->middleware('role:Teacher');
        Route::get('/editslots/{id}', 'Teacher\SlotController@edit')->name('edit.slots')->middleware('role:Teacher');
        Route::post('/updateslots/{id}', 'Teacher\SlotController@update')->name('update.slots')->middleware('role:Teacher');
        Route::get('/deleteslots/{id}', 'Teacher\SlotController@delete')->name('delete.slots')->middleware('role:Teacher');


        // For Activities
        Route::get('/activity', 'Teacher\ActivityController@index')->name('all.activity')->middleware('role:Teacher');
        Route::get('/newactivity', 'Teacher\ActivityController@create')->name('new.activity')->middleware('role:Teacher');
        Route::post('/storeactivity', 'Teacher\ActivityController@store')->name('store.activity')->middleware('role:Teacher');
        Route::get('/editactivity/{id}', 'Teacher\ActivityController@editactivity')->name('edit.activity')->middleware('role:Teacher');
        Route::post('/updateactivity', 'Teacher\ActivityController@updateactivity')->name('update.activity')->middleware('role:Teacher');
        Route::get('/viewactivity/{id}', 'Teacher\ActivityController@viewactivity')->name('view.thactivity')->middleware('role:Teacher');

        // For My Porposal
        Route::get('/proposal', 'Teacher\MyPorposalController@index')->name('all.proposal')->middleware('role:Teacher');
        Route::post('/storeproposal', 'Teacher\MyPorposalController@store')->name('store.proposal')->middleware('role:Teacher');
        Route::get('/editproposal/{id}', 'Teacher\MyPorposalController@edit')->name('edit.proposal')->middleware('role:Teacher');
        Route::post('/updateproposal/{id}', 'Teacher\MyPorposalController@update')->name('update.proposal')->middleware('role:Teacher');
        Route::get('/deleteproposal/{id}', 'Teacher\MyPorposalController@delete')->name('delete.proposal')->middleware('role:Teacher');

    });

    Route::group(['middlerware' => 'role:Committee'], function() {
        Route::post('/meetingresponse', 'committe\SchedulerController@meetingstatus')->name('store.response')->middleware('role:Committee');
        Route::get('/schedule', 'committe\SchedulerController@index')->name('show.scheduler');

    });
});
require __DIR__.'/auth.php';

app/Http/Controllers/Student/SchedulerController.php
<?php

namespace App\Http\Controllers\Student;

use App\Models\User;
use App\Models\PivotGroup;
use App\Models\GroupScheduler;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SchedulerController extends Controller
{
    public function index(){

        $data['teachercount'] = 0;
        $data['page_slug'] = request()->route()->uri();
        $data['teachers'] = User::role('Teacher')->get();
        $groupId = PivotGroup::where(['student_id'=> Auth::id()])->first();
        if($groupId){
            $data['scheduler'] = GroupScheduler::with('timeslot','group','panelteacher.teacher')->where('group_id',$groupId->group_id)->get();
            if(count($data['scheduler']) != 0){
                $data['teachercount'] = $data['scheduler'][0]->panelteacher->groupBy('teacher_id')->count();
            }
        }
        // dd($data['scheduler'][0]->panelteacher[0]->teacher);
        return view('fyp.groupscheduler.index',$data);
    }
}

app/Http/Controllers/Student/StudentGroupController.php
<?php

namespace App\Http\Controllers\Student;

use Carbon\Carbon;
use App\Models\User;
use App\Models\Group;
use App\Models\Student;
use App\Models\Teacher;
use App\Models\MyPorposal;
use App\Models\PivotGroup;
use App\Models\StudentMeta;
use App\Models\GroupComment;
use Illuminate\Http\Request;
use App\Jobs\GroupRequestEmail;
use App\Models\DataofSubmission;
use App\Notifications\GroupRequest;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use PHPUnit\TextUI\XmlConfiguration\Groups;
use Illuminate\Support\Facades\Notification;
use App\Http\Controllers\admin\StudentController;

class StudentGroupController extends Controller
{
    public function viewgroup(){
        $data['page_slug'] = request()->route()->uri();
        $data['datetime'] = DataofSubmission::where('type','1')->first();
        if($data['datetime']){
            $data['convertedate'] = Carbon::parse($data['datetime']->date)->format('Y-m-d h:i A');
        }
        $data['teachers'] = User::role('Teacher')->get();
        $data['students'] = User::role('Student')->where('is_group', 0 )->get();
        $data['checkgroup'] = User::role('Student')->with(['stdgroup'])->where(['id' => Auth::id() , 'is_group' => 1 ])->first();
        if($data['checkgroup'] !=  null){
            $data['proposal'] = MyPorposal::with('group')->where(['teacher_id' => $data['checkgroup']->stdgroup->teacher_id, 'group_id' => $data['checkgroup']->stdgroup->group_id])->first();
            $data['comment'] = GroupComment::with('teacher')->where('group_id', $data['checkgroup']->stdgroup->group_id )->get();
        }
        return view('fyp.Studentside.groupadd',$data);
    }

    public function addgroup(Request $request){
        $data['page_slug'] = request()->route()->uri();
        $request->validate([
            'title'=>'required',
            'teachers'=>["required","array","min:1","max:3"],
            'students'=>["required","array","min:3","max:4"],
            'description'=>'required',
            'proposal'=>'required|mimes:pdf,doc,docx,xlsx|max:10000',
            ]);

            $data =[
                'title'=>$request->title,
                'description'=>$request->description,
            ];

            if ($request->hasFile('proposal')) {
                $imagePath = $request->file('proposal');
                $imageName  = uniqid('', true) . '.' . $imagePath->getClientOriginalExtension();
                $path = $request->file('proposal')->storeAs('projectporpsal', $imageName, 'public');
                $data['path'] = $path;
            }

        $LastestGroup = Group::create($data)->id;

        if($LastestGroup){
            $groupleader = StudentMeta::create([
                'student_id' => Auth::id(),
                'group_leader' => '1',
            ]);

            // For Email Notificaion of Group Request
            $groupData = [
                'body' => [
                    'Group_Title' => $request->title,
                    'Group_Description' => $request->description,
                ],
                'data' => 'Group Details',
                'url' => url('/request/'.$LastestGroup),
                'thankyou' => 'Please check group request before deadline',
            ];
            $teacherData = User::find($request->teachers);
            Notification::send($teacherData, new GroupRequest($groupData));
        }

        foreach ($request->students as $stid)
        {
            foreach ($request->teachers as $tdid){

                $data =[
                    'group_id'=> $LastestGroup,
                    'student_id'=> $stid,
                    'teacher_id'=> $tdid,
                ];

                PivotGroup::create($data);
            }
            User::where('id',$stid )->update(['is_group' => 1]);
        }

        return redirect()->route('dashboard');
    }

    public function updateProposal(Request $request){
        // dd($request->group_id);
        $file = $request->file('new_proposal');
        $originalname = $file->getClientOriginalName();
        $path = $file->storeAs('projectporpsal', $originalname, 'public');
        $updateProposal = Group::where('id', $request->group_id)->update([
            'title'=>$request->title,
            'description'=>$request->description,
            'path' => $path,
            'teacher_proposal' => $request->proposal_id,
        ]);
        if($updateProposal){
            return back()->with('update','Proposal has been update successfully');
        }
    }
}

app/Http/Controllers/Student/ViewMarksController.php
<?php

namespace App\Http\Controllers\Student;

use App\Models\Marks;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ViewMarksController extends Controller
{
    public function viewmarks(){
        // dd(Auth::id());
        $data['page_slug'] = request()->route()->uri();
        $data['marks'] = Marks::where('student_id' , Auth::id())->get();
        return view ('fyp.Studentside.view_marks' , $data);
    }

    public function adminviewmarks(){
        // dd(Auth::id());
        $data['page_slug'] = request()->route()->uri();
        $data['marks'] = Marks::with('groups','student','teacher')->get();
        // dd($data['marks']);
        return view ('fyp.marks.index' , $data);
    }
}

resources/views/fyp/student/create-student.blade.php
@extends('fyp.layouts.app')
@section('content')
<div class="card card-custom">
    <div class="card-header">
        <h3 class="card-title">
            New Student
        </h3>
    </div>
    <!--begin::Form-->
    <form action="{{ route('student.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="card-body">

            <div class="form-group row">
                <label class="col-2 col-form-label">Roll NO</label>
                <div class="col-10">
                    <input class="form-control" type="text" name="roll_no" id="example-text-input" placeholder="Enter roll no" required/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-2 col-form-label">Enrollment NO</label>
                <div class="col-10">
                    <input class="form-control" type="text" name="enrollment_no" id="example-text-input" placeholder="Enter roll no" required/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-2 col-form-label">Name</label>
                <div class="col-10">
                    <input class="form-control" type="text" name="name" id="example-text-input" placeholder="Enter name" required/>
                </div>
            </div>
            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Phone No</label>
                <div class="col-10">
                    <input class="form-control" type="tel" name="phone" id="example-text-input" placeholder="Enter phone" required/>
                </div>
            </div>
            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">CGPA</label>
                <div class="col-10">
                    <input class="form-control" type="number" name="cgpa" id="example-text-input" placeholder="Enter cgpa" step=0.001 required/>
                </div>
            </div>
            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Cloud ID</label>
                <div class="col-10">
                    <input class="form-control" type="email" name="email" id="example-text-input" placeholder="Enter email" required/>
                </div>
            </div>

        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-2">
                    <button type="submit" class="btn btn-success btn-lg btn-block">Save</button>
                </div>
                <div class="col-10">
                </div>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/fyp/student/student.blade.php
@extends('fyp.layouts.app')
@section('content')
<div class="card card-custom">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
            <h3 class="card-label">Student</h3>
        </div>
        <div class="card-toolbar">
            <!--begin::Dropdown-->
            <div class="dropdown dropdown-inline mr-2">
                <button type="submit" class="btn btn-light-primary font-weight-bolder"  data-toggle="modal" data-target="#ImportModal">
                    <span class="svg-icon svg-icon-md">
                        <i class="fas fa-file-upload"></i>
                    </span>Import</button>
            </div>
            <!--end::Dropdown-->
            <!--begin::Button-->
            <a href="{{ route('student.create') }}" class="btn btn-primary font-weight-bolder">
                <span class="svg-icon svg-icon-md">
                    <i class="fa fa-plus-circle"></i>
                </span>New Record</a>
            <!--end::Button-->
        </div>
    </div>
    <div class="card-body">
        <!--begin: Search Form-->
        <!--begin::Search Form-->
        <div class="mb-7">
            <div class="row align-items-center">
                <div class="col-lg-3">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="input-icon">
                                <input type="text" class="form-control" placeholder="Search..."
                                    id="kt_datatable_search_query" />
                                <span>
                                    <i class="flaticon2-search-1 text-muted"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-xl-4 mt-5 mt-lg-0">
                    <a href="#" class="btn btn-light-primary px-6 font-weight-bold">Search</a>
                </div>
            </div>
        </div>
        <!--end::Search Form-->
        <!--end: Search Form-->
        <!--begin: Datatable-->
        <div class="panel panel-default">
            @if (session('success'))
                <div class="alert alert-success">{{ session('success') }}</div>
            @elseif (session('delete'))
                <div class="alert alert-danger">{{ session('delete') }}</div>
            @elseif (session('update'))
                <div class="alert alert-success">{{ session('update') }}</div>
            @endif
        </div>
        <br>
        <table class="datatable datatable-bordered datatable-head-custom table-striped" id="kt_datatable">
            <thead>
                <tr>
                    <th >Sr No</th>
                    <th title="Field #4">Roll No</th>
                    <th title="Field #4">Enrollment NO</th>
                    <th title="Field #5">Name</th>
                    <th title="Field #4">Phone</th>
                    <th title="Field #2">CGPA</th>
                    <th title="Field #4">Cloud ID</th>
                    <th title="Field #6">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($student as $index => $data)
                <tr>
                    <td >{{++$index}}</td>
                    <td>{{$data->roll_no}}</td>
                    <td>{{$data->enrollment_no}}</td>
                    <td class="text-right">{{$data->name}}</td>
                    <td class="text-right">{{$data->phone}}</td>
                    <td class="text-right">{{$data->cgpa}}</td>
                    <td class="text-right">{{$data->email}}</td>
                    <td data-field="Actions" data-autohide-disabled="false" aria-label="null" class="datatable-cell">
                        <span style="overflow: visible; position: relative; width: 125px;">
                        <a href="{{ route('student.edit',$data->id) }}" class="btn btn-sm btn-clean btn-icon mr-2" title="Edit details">
                                <span class="svg-icon svg-icon-md">
                                    <i class="fas fa-pen"></i>
                                </span>
                            </a>
                            {{-- <form method="Post" action="{{ route('student.destroy',$data->id) }}" style="display: -webkit-inline-box;">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-clean btn-icon" title="Delete">
                                    <span class="svg-icon svg-icon-md">
                                        <i class="fas fa-trash"></i>
                                    </span>
                                </button>
                            </form> --}}
                        </span>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <!--end: Datatable-->
    </div>
</div>
  <!-- Modal -->
  <div class="modal fade" id="ImportModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Upload File</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{{ route('import.student') }}" enctype="multipart/form-data" method="POST">
            @csrf
            <div class="modal-body">
                <div class="form-group">
                    <label>Student File</label>
                    <input type="file" name="file" class="form-control form-control-solid" style="height:50px;"/>
                   </div>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Upload</button>
            </div>
        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/fyp/student/update-student.blade.php
@extends('fyp.layouts.app')
@section('content')
<div class="card card-custom">
    <div class="card-header">
        <h3 class="card-title">
            Update Student
        </h3>
    </div>
    <!--begin::Form-->
    <form action="{{ route('student.update', $student->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        {{ csrf_field() }}
        {{ method_field('PUT') }}
        <div class="card-body">

            <div class="form-group row">
                <label class="col-2 col-form-label">Roll NO</label>
                <div class="col-10">
                    <input class="form-control" type="hidden" name="id" value="{{$student->id}}" required/>
                    <input class="form-control" type="text" name="roll_no" id="example-text-input" placeholder="Enter roll no" value="{{$student->roll_no}}" required/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-2 col-form-label">Enrollment NO</label>
                <div class="col-10">
                    <input class="form-control" type="text" name="enrollment_no" id="example-text-input" placeholder="Enter roll no" value="{{$student->enrollment_no}}" required/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-2 col-form-label">Name</label>
                <div class="col-10">
                    <input class="form-control" type="text" name="name" id="example-text-input" placeholder="Enter name" value="{{$student->name}}" required/>
                </div>
            </div>
            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Phone No</label>
                <div class="col-10">
                    <input class="form-control" type="tel" name="phone" id="example-text-input" placeholder="Enter phone"  value="{{$student->phone}}" required/>
                </div>
            </div>
            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">CGPA</label>
                <div class="col-10">
                    <input class="form-control" type="number" name="cgpa" step="0.001" id="example-text-input" placeholder="Enter cgpa"  value="{{$student->cgpa}}" required/>
                </div>
            </div>
            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Cloud ID</label>
                <div class="col-10">
                    <input class="form-control" type="email" name="email" id="example-text-input" placeholder="Enter email"  value="{{$student->email}}" required/>
                </div>
            </div>

        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-2">
                    <button type="submit" class="btn btn-success btn-lg btn-block">Update</button>
                </div>
                <div class="col-10">
                </div>
            </div>
        </div>
    </form>
</div>
@endsection