routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
});

Route::middleware(['auth','role:Admin|Teacher|Student|Committee'])->group(function () {

    // For Notes
    Route::resource('/note', 'admin\NoteController')->middleware('role:Admin');

    // For Change Password
    Route::get('/change_password', 'admin\DashboradController@changepassword')->name('change.password');
    Route::post('/updatepassword', 'admin\DashboradController@updatepassword')->name('update.password');

    // For Group scheduler
    Route::get('/scheduler', 'admin\GroupSchedulerController@index')->name('index.scheduler');
    Route::post('/scheduler', 'admin\GroupSchedulerController@generate')->name('store.scheduler')->middleware('role:Admin');

    //For Date of submission
    Route::get('/setdates', 'admin\DateofSubmissionController@index')->name('index.date')->middleware('role:Admin');
    Route::post('/storedate', 'admin\DateofSubmissionController@store')->name('store.date')->middleware('role:Admin');
    Route::get('/editdate/{id}', 'admin\DateofSubmissionController@edit')->name('edit.date')->middleware('role:Admin');
    Route::post('/updatedate', 'admin\DateofSubmissionController@update')->name('update.date')->middleware('role:Admin');

    //For Marks
    Route::get('/adminviewmarks', 'Student\ViewMarksController@adminviewmarks')->name('admin.showmarks')->middleware('role:Admin');

    //For All Activites Show
    Route::get('/adminactivity', 'Teacher\ActivityController@adminindex')->name('all.adminactivity')->middleware('role:Admin');
    Route::get('/detialsactivity/{id}', 'Teacher\ActivityController@adminviewactivity')->name('details.activity')->middleware('role:Admin');

    // For View of Pervious FYP Data
    Route::get('/perviousfyp', 'admin\LastFypDataController@index')->name('all.lastfyp');
    Route::get('/newperviousfyp', 'admin\LastFypDataController@edit_data')->name('new.lastfyp')->middleware('role:Admin');
    Route::post('/storeperviousfyp', 'admin\LastFypDataController@store_data')->name('store.lastfyp')->middleware('role:Admin');
    Route::get('/deleteperviousfyp/{id}', 'admin\LastFypDataController@deleteperviousfyp')->name('delete.lastfyp')->middleware('role:Admin');
    Route::get('keywordserach', 'admin\LastFypDataController@keywordserach' )->name('keyword.search');

    // Admin Side
    Route::get('/dashboard', 'admin\DashboradController@index')->name('dashboard');
    Route::resource('/teacher', 'admin\TeacherController')->middleware('role:Admin');
    Route::resource('/student', 'admin\StudentController')->middleware('role:Admin');
    Route::post('/import', 'admin\ImportController@stdImport')->name('import.student')->middleware('role:Admin');
    Route::post('/thimport', 'admin\ImportController@TeacherImport')->name('import.teacher')->middleware('role:Admin');

    //Slots of All Teacher
    Route::get('/allslots', 'admin\AllSlotsController@index')->name('slots');

    //All Groups
    Route::get('/allgroups', 'admin\GroupsController@index')->name('admin.groups');
    Route::get('/groupdetials/{id}', 'admin\GroupsController@groupdetials')->name('detials.groups');
    Route::post('/assigngroup', 'admin\GroupsController@assigngroup')->name('assign.groups');

    // For Committee Members
    Route::get('/committee', 'admin\CommitteController@index')->name('all.committee')->middleware('role:Admin');
    Route::post('/committee', 'admin\CommitteController@store')->name('store.committee')->middleware('role:Admin');

    // Student Side
    Route::group(['middlerware' => 'role:Student'], function() {

        // For Scheduler
        Route::get('/stdschedule', 'Student\SchedulerController@index')->name('std.scheduler')->middleware('role:Student');


        // For add group student
        Route::get('/group', 'Student\StudentGroupController@viewgroup')->name('view.group')->middleware('role:Student');
        Route::post('/group', 'Student\StudentGroupController@addgroup')->name('add.group')->middleware('role:Student');

        // For Proposal Update
        Route::post('/upproposal', 'Student\StudentGroupController@updateProposal')->name('up.proposal')->middleware('role:Student');

        // For Marks
        Route::get('/viewmarks', 'Student\ViewMarksController@viewmarks')->name('show.marks')->middleware('role:Student');

        // For Activity Store
        Route::get('/stdactivity', 'Teacher\ActivityController@stdindex')->name('std.activity')->middleware('role:Student');
        Route::get('/viewstdactivity/{id}', 'Teacher\ActivityController@stdactivityview')->name('view.activity')->middleware('role:Student');
        Route::post('/storestdactivity', 'Teacher\ActivityController@stdstore')->name('store.stdactivity')->middleware('role:Student');


    });

    // Teacher Side
    Route::group(['middlerware' => 'role:Teacher'], function() {

        // For Panel Meeting
        Route::get('/panelmeeting', 'admin\GroupSchedulerController@panelindex')->name('panel.meeting')->middleware('role:Teacher');
        Route::post('/panelmeeting', 'committe\SchedulerController@panelmeetingstatus')->name('panelmeeting.store');
        Route::get('/groupfeedback/{id}', 'Teacher\MarksController@groupfeedback')->name('group.feeback');


        // For Group
        Route::get('/request/{id}', 'Teacher\TeacherGroupController@viewgrouprequest')->name('view.grouprequest')->middleware('role:Teacher');
        Route::get('/download/{id}', 'Teacher\TeacherGroupController@downloadproposal')->name('download.proposal')->middleware('role:Teacher');
        Route::post('/approved-group/{id}', 'Teacher\TeacherGroupController@groupapproved')->name('group.approved')->middleware('role:Teacher');
        Route::post('/rejected-group/{id}', 'Teacher\TeacherGroupController@groupRejected')->name('group.rejected')->middleware('role:Teacher');
        Route::get('/groups', 'Teacher\TeacherGroupController@groups')->name('all.groups')->middleware('role:Teacher');

        // For Marks
        Route::get('/marks', 'Teacher\MarksController@index')->name('group.marks')->middleware('role:Teacher');
        Route::get('/groupmarks/{id}', 'Teacher\MarksController@groupmarks')->name('add.marks')->middleware('role:Teacher');
        Route::get('/add-marks/{groupid}/{studentid}','Teacher\MarksController@edit')->name('marks.edit')->middleware('role:Teacher');
        Route::post('/add-marks/{groupid}/{studentid}','Teacher\MarksController@edit')->name('marks.edit')->middleware('role:Teacher');

        // For Slots
        Route::get('/slots', 'Teacher\SlotController@index')->name('all.slots')->middleware('role:Teacher|Student');
        Route::post('/addslots', 'Teacher\SlotController@store')->name('store.slots')->middleware('role:Teacher');
        Route::get('/editslots/{id}', 'Teacher\SlotController@edit')->name('edit.slots')->middleware('role:Teacher');
        Route::post('/updateslots/{id}', 'Teacher\SlotController@update')->name('update.slots')->middleware('role:Teacher');
        Route::get('/deleteslots/{id}', 'Teacher\SlotController@delete')->name('delete.slots')->middleware('role:Teacher');


        // For Activities
        Route::get('/activity', 'Teacher\ActivityController@index')->name('all.activity')->middleware('role:Teacher');
        Route::get('/newactivity', 'Teacher\ActivityController@create')->name('new.activity')->middleware('role:Teacher');
        Route::post('/storeactivity', 'Teacher\ActivityController@store')->name('store.activity')->middleware('role:Teacher');
        Route::get('/editactivity/{id}', 'Teacher\ActivityController@editactivity')->name('edit.activity')->middleware('role:Teacher');
        Route::post('/updateactivity', 'Teacher\ActivityController@updateactivity')->name('update.activity')->middleware('role:Teacher');
        Route::get('/viewactivity/{id}', 'Teacher\ActivityController@viewactivity')->name('view.thactivity')->middleware('role:Teacher');

        // For My Porposal
        Route::get('/proposal', 'Teacher\MyPorposalController@index')->name('all.proposal')->middleware('role:Teacher');
        Route::post('/storeproposal', 'Teacher\MyPorposalController@store')->name('store.proposal')->middleware('role:Teacher');
        Route::get('/editproposal/{id}', 'Teacher\MyPorposalController@edit')->name('edit.proposal')->middleware('role:Teacher');
        Route::post('/updateproposal/{id}', 'Teacher\MyPorposalController@update')->name('update.proposal')->middleware('role:Teacher');
        Route::get('/deleteproposal/{id}', 'Teacher\MyPorposalController@delete')->name('delete.proposal')->middleware('role:Teacher');

    });

    Route::group(['middlerware' => 'role:Committee'], function() {
        Route::post('/meetingresponse', 'committe\SchedulerController@meetingstatus')->name('store.response')->middleware('role:Committee');
        Route::get('/schedule', 'committe\SchedulerController@index')->name('show.scheduler');

    });
});
require __DIR__.'/auth.php';

app/Models/Note.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    use HasFactory;
    protected $guarded = [];

}

app/Http/Controllers/admin/NoteController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Note;
use Illuminate\Http\Request;

class NoteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['page_slug'] = request()->route()->uri();
        $data['note'] = Note::get();
        return view('fyp.notes.index',  $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $notes = Note::create([
            'title' => $request->title,
            'note' => $request->note,
        ]);
        if($notes){
            return redirect('/note')->with(['success' => 'Note is successfully added']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $note = Note::find($id)->delete();
        if($note){
            return redirect('/note')->with(['delete' => 'Note is successfully delete']);
        }
    }
}

resources/views/fyp/notes/index.blade.php
@extends('fyp.layouts.app')
@section('content')
<!--begin::Entry-->
<div class="panel panel-default">
    @if (session('success'))
        <div class="alert alert-success">{{ session('success') }}</div>
    @elseif (session('delete'))
        <div class="alert alert-danger">{{ session('delete') }}</div>
    @elseif (session('update'))
        <div class="alert alert-success">{{ session('update') }}</div>
    @endif
</div>
<div class="d-flex flex-column-fluid">
    <!--begin::Container-->
    <div class="container">
        <!--begin::Card-->
        <div class="card card-custom card-sticky" id="kt_page_sticky_card">
            <div class="card-header">
                <div class="card-title">
                    <h3 class="card-label">Sticky Notes
                    </h3>
                </div>
                <div class="card-toolbar">
                    <div class="btn-group">
                        <form class="form" id="kt_form" method="POST" action="{{ route('note.store') }}">
                            @csrf
                        <button type="submit" class="btn btn-primary font-weight-bolder">
                            <i class="ki ki-check icon-xs"></i>Save Note</button>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <!--begin::Form-->
                    <div class="row">
                        <div class="col-xl-2"></div>
                        <div class="col-xl-8">
                            <div class="my-5">
                                <div class="form-group row">
                                    <label class="col-2">Title</label>
                                    <div class="col-10">
                                        <input class="form-control" name="title" type="text"
                                            placeholder="Enter the title of note" required/>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-2">Note</label>
                                    <div class="col-10">
                                        <textarea class="form-control" name="note" type="text"
                                            placeholder="Enter the title of note" rows="5" required></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <!--end::Form-->
            </div>
        </div>
        <!--end::Card-->
    </div>
    <!--end::Container-->
</div>
<!--end::Entry-->
<!--begin::Entry-->
<div class="d-flex flex-column-fluid pt-7">
    <!--begin::Container-->
    <div class="container">
        <!--begin::Example-->
        <!--begin::Row-->
        <div class="row">
            {{-- @dd($note->count()) --}}
            @if ($note->count() != 0)
                @foreach ($note as $data)
                    <div class="col-lg-6 pt-2">
                        <!--begin::Example-->
                        <!--begin::Card-->
                        <div class="card card-custom" data-card="true" id="kt_card_3">
                            <div class="card-header">
                                <div class="card-title">
                                    <h3 class="card-label">{{ $data->title }}</h3>
                                </div>
                                <div class="card-toolbar">
                                    <a href="#" class="btn btn-icon btn-circle btn-sm btn-light-primary mr-1"
                                        data-card-tool="toggle">
                                        <i class="ki ki-arrow-down icon-nm"></i>
                                    </a>
                                    <form action="{{ route('note.destroy', $data->id) }}" method="POST">
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <button class="btn btn-icon btn-circle btn-sm btn-light-danger">
                                            <i class="ki ki-close icon-nm"></i>
                                        </button>
                                    </form>
                                </div>
                            </div>
                            <div class="card-body">
                                <p>{{ $data->note }}</p>
                            </div>
                        </div>
                        <!--end::Card-->
                        <!--end::Example-->
                    </div>
                @endforeach
            @else
            <div class="col-lg-6">
                <!--begin::Example-->
                <!--begin::Card-->
                <div class="card card-custom" data-card="true" id="kt_card_3">
                    <div class="card-header">
                        <div class="card-title">
                            <h3 class="card-label">Title</h3>
                        </div>
                        <div class="card-toolbar">
                            <a href="#" class="btn btn-icon btn-circle btn-sm btn-light-primary mr-1"
                                data-card-tool="toggle">
                                <i class="ki ki-arrow-down icon-nm"></i>
                            </a>
                            <button class="btn btn-icon btn-circle btn-sm btn-light-danger">
                                <i class="ki ki-close icon-nm"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has ..</p>
                    </div>
                </div>
                <!--end::Card-->
                <!--end::Example-->
            </div>
            @endif
        </div>
        <!--end::Row-->
        <!--end::Example-->
    </div>
    <!--end::Container-->
</div>
<!--end::Entry-->
@endsection